Repository eclipse/openvsx, pull requests merged in 2023-01, with the labels that each got.

#642 Implement sponsor link
  server/build.gradle
  server/src/main/java/org/eclipse/openvsx/AdminAPI.java
  server/src/main/java/org/eclipse/openvsx/ExtensionProcessor.java
  server/src/main/java/org/eclipse/openvsx/ExtensionService.java
  server/src/main/java/org/eclipse/openvsx/ExtensionValidator.java
  server/src/main/java/org/eclipse/openvsx/IExtensionRegistry.java
  server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
  server/src/main/java/org/eclipse/openvsx/RegistryAPI.java
  server/src/main/java/org/eclipse/openvsx/UpstreamRegistryService.java
  server/src/main/java/org/eclipse/openvsx/UserAPI.java
  server/src/main/java/org/eclipse/openvsx/UserService.java
  server/src/main/java/org/eclipse/openvsx/adapter/ExtensionQueryResult.java
  server/src/main/java/org/eclipse/openvsx/adapter/LocalVSCodeService.java
  server/src/main/java/org/eclipse/openvsx/cache/CacheService.java
  server/src/main/java/org/eclipse/openvsx/entities/ExtensionVersion.java
  server/src/main/java/org/eclipse/openvsx/entities/Namespace.java
  server/src/main/java/org/eclipse/openvsx/json/ExtensionJson.java
  server/src/main/java/org/eclipse/openvsx/json/NamespaceDetailsJson.java
  server/src/main/java/org/eclipse/openvsx/json/SearchEntryJson.java
  server/src/main/java/org/eclipse/openvsx/repositories/ExtensionVersionJooqRepository.java
  server/src/main/java/org/eclipse/openvsx/storage/AzureBlobStorageService.java
  server/src/main/java/org/eclipse/openvsx/storage/GoogleCloudStorageService.java
  server/src/main/java/org/eclipse/openvsx/storage/IStorageService.java
  server/src/main/java/org/eclipse/openvsx/storage/StorageUtilService.java
  server/src/main/java/org/eclipse/openvsx/web/ShallowEtagHeaderFilter.java
  server/src/main/jooq-gen/org/eclipse/openvsx/jooq/Keys.java
  server/src/main/jooq-gen/org/eclipse/openvsx/jooq/Public.java
  server/src/main/jooq-gen/org/eclipse/openvsx/jooq/Tables.java
  server/src/main/jooq-gen/org/eclipse/openvsx/jooq/tables/ExtensionVersion.java
  server/src/main/jooq-gen/org/eclipse/openvsx/jooq/tables/Namespace.java
  server/src/main/jooq-gen/org/eclipse/openvsx/jooq/tables/NamespaceSocialLinks.java
  server/src/main/jooq-gen/org/eclipse/openvsx/jooq/tables/records/ExtensionVersionRecord.java
  server/src/main/jooq-gen/org/eclipse/openvsx/jooq/tables/records/NamespaceRecord.java
  server/src/main/jooq-gen/org/eclipse/openvsx/jooq/tables/records/NamespaceSocialLinksRecord.java
  server/src/main/resources/db/migration/V1_30__Namespace_Details.sql
  server/src/main/resources/db/migration/V1_31__ExtensionVersion_SponsorLink.sql
  server/src/main/resources/ehcache.xml
  server/src/test/java/org/eclipse/openvsx/UserAPITest.java
  server/src/test/java/org/eclipse/openvsx/adapter/VSCodeAPITest.java
  webui/package.json
  webui/src/extension-registry-service.ts
  webui/src/extension-registry-types.ts
  webui/src/main.tsx
  webui/src/pages/extension-detail/extension-detail.tsx
  webui/src/pages/namespace-detail/namespace-detail.tsx
  webui/src/pages/user/create-namespace-dialog.tsx
  webui/src/pages/user/user-namespace-details.tsx
  webui/src/pages/user/user-settings-namespace-detail.tsx
  webui/yarn.lock
Labels: enhancement, webui, server, priority:high

#658 Can't search @category:"language packs" correctly in Code - OSS
  server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java
Labels: priority:high

#656 Search should not be case sensitive
  .gitpod.dockerfile
  server/build.gradle
  server/src/main/java/org/eclipse/openvsx/search/ElasticSearchService.java
  server/src/test/java/org/eclipse/openvsx/TestSearchConfig.java
Labels: priority:high

#657 add restAPI for downloading latest version of an extension
  server/src/main/java/org/eclipse/openvsx/LocalRegistryService.java
  server/src/test/java/org/eclipse/openvsx/RegistryAPITest.java
Labels: priority:low

#252 Added download terms to page settings object, use in detailed overview
  webui/package.json
  webui/src/page-settings.ts
  webui/src/pages/extension-detail/extension-detail-overview.tsx
Labels: priority:medium
