Repository eclipse/openvsx, pull requests merged in 2023-02, with the labels that each got.

#661 Access token dialog improvements
  webui/src/pages/user/generate-token-dialog.tsx
  webui/src/pages/user/user-settings-tokens.tsx
Labels: webui, priority:low

#469 [Admin] Add Ability to Change Namespace
  server/src/main/java/org/eclipse/openvsx/AdminAPI.java
  server/src/main/java/org/eclipse/openvsx/AdminService.java
  server/src/main/java/org/eclipse/openvsx/json/ChangeNamespaceJson.java
  server/src/test/java/org/eclipse/openvsx/AdminAPITest.java
  webui/src/extension-registry-service.ts
  webui/src/pages/admin-dashboard/namespace-admin.tsx
  webui/src/pages/admin-dashboard/namespace-change-dialog.tsx
  webui/src/pages/user/user-namespace-member-list.tsx
  webui/src/pages/user/user-settings-namespace-detail.tsx
Labels: priority:medium

#460 Add a way to proxy upstream requests instead of external links
  server/src/main/java/org/eclipse/openvsx/UpstreamProxyService.java
  server/src/main/java/org/eclipse/openvsx/UpstreamRegistryService.java
  server/src/main/java/org/eclipse/openvsx/adapter/UpstreamVSCodeService.java
Labels: priority:low
